from django.urls import path
from . import views

urlpatterns = [
    path('', views.std_login, name='std_login'),
    path('my/', views.mySubjects, name='mySubjects'),
    path('teacherSubjects/', views.teacherSubjects, name='teacherSubjects'),
    path('login/', views.std_login, name='std_login'),
    path('logout/', views.std_logout, name='std_logout'),
    path('my/<int:code>/', views.subject_page, name='subject'),
    path('profile/<str:id>/', views.profile, name='profile'),
    path('teacherProfile/<str:id>/', views.profile, name='profile_teacher'),
    path('teacher/<int:code>/', views.subject_page_teacher, name='teacher'),
    path('addAnnouncement/<int:code>/',
         views.addAnnouncement, name='addAnnouncement'),
    path('announecement/<int:code>/<int:id>/',
         views.deleteAnnouncement, name='deleteAnnouncement'),
    path('edit/<int:code>/<int:id>/',
         views.editAnnouncement, name='editAnnouncement'),
    path('update/<int:code>/<int:id>/',
         views.updateAnnouncement, name='updateAnnouncement'),
    path('addAssignment/<int:code>/', views.addAssignment, name='addAssignment'),
    path('assignment/<int:code>/<int:id>/',
         views.assignmentPage, name='assignmentPage'),
    path('assignments/<int:code>/', views.allAssignments, name='allAssignments'),
    path('student-assignments/<int:code>/',
         views.allAssignmentsSTD, name='student-assignments'),
    path('addSubmission/<int:code>/<int:id>/',
         views.addSubmission, name='addSubmission'),
    path('submission/<int:code>/<int:id>/',
         views.viewSubmission, name='submission'),
    path('gradeSubmission/<int:code>/<int:id>/<int:sub_id>',
         views.gradeSubmission, name='gradeSubmission'),
    path('subject-material/<int:code>/',
         views.addSubjectMaterial, name='addSubjectMaterial'),
    path('subject-material/<int:code>/<int:id>/',
         views.deleteSubjectMaterial, name='deleteSubjectMaterial'),
    path('subjects/', views.subjects, name='subjects'),
    path('levels/', views.levels, name='levels'),
    path('access/<int:code>/', views.access, name='access'),
    path('changePasswordPrompt/', views.changePasswordPrompt,
         name='changePasswordPrompt'),
    path('changePhotoPrompt/', views.changePhotoPrompt, name='changePhotoPrompt'),
    path('changePassword/', views.changePassword, name='changePassword'),
    path('changePasswordTeacher/', views.changePasswordTeacher,
         name='changePasswordTeacher'),
    path('changePhoto/', views.changePhoto, name='changePhoto'),
    path('changePhotoTeacher/', views.changePhotoTeacher,
         name='changePhotoTeacher'),
    path('search/', views.search, name='search'),
    path('error/', views.error, name='error'),
]
