from django.urls import path
from . import views

urlpatterns = [
    path('', views.std_login, name='std_login'),
    path('my/', views.mySubjects, name='mySubjects'),
    path('teacherSubjects/', views.teacherSubjects, name='teacherSubjects'),
    path('login/', views.std_login, name='std_login'),
    path('logout/', views.std_logout, name='std_logout'),
    path('my/<str:code>/', views.subject_page, name='subject'),
    path('profile/<str:id>/', views.profile, name='profile'),
    path('teacherProfile/<str:id>/', views.profile, name='profile_teacher'),
    path('teacher/<str:code>/', views.subject_page_teacher, name='teacher'),
    path('addAnnouncement/<str:code>/',
         views.addAnnouncement, name='addAnnouncement'),
    path('announecement/<str:code>/<str:id>/',
         views.deleteAnnouncement, name='deleteAnnouncement'),
    path('edit/<str:code>/<str:id>/',
         views.editAnnouncement, name='editAnnouncement'),
    path('update/<str:code>/<str:id>/',
         views.updateAnnouncement, name='updateAnnouncement'),
    path('addAssignment/<str:code>/', views.addAssignment, name='addAssignment'),
    path('addWeeklyPlan/<str:code>/', views.addWeeklyPlan, name='addWeeklyPlan'),
    path('assignment/<str:code>/<str:id>/',
         views.assignmentPage, name='assignmentPage'),
    path('assignments/<str:code>/', views.allAssignments, name='allAssignments'),
    path('student-assignments/<str:code>/',
         views.allAssignmentsSTD, name='student-assignments'),
    path('addSubmission/<str:code>/<str:id>/',
         views.addSubmission, name='addSubmission'),
    path('submission/<str:code>/<str:id>/',
         views.viewSubmission, name='submission'),
    path('gradeSubmission/<str:code>/<str:id>/<str:sub_id>',
         views.gradeSubmission, name='gradeSubmission'),
    path('subject-material/<str:code>/',
         views.addSubjectMaterial, name='addSubjectMaterial'),
    path('subject-material/<str:code>/<str:id>/',
         views.deleteSubjectMaterial, name='deleteSubjectMaterial'),
    path('subjects/', views.subjects, name='subjects'),
    path('levels/', views.levels, name='levels'),
    path('access/<str:code>/', views.access, name='access'),
    path('changePasswordPrompt/', views.changePasswordPrompt,
         name='changePasswordPrompt'),
    path('changePhotoPrompt/', views.changePhotoPrompt, name='changePhotoPrompt'),
    path('changePassword/', views.changePassword, name='changePassword'),
    path('changePasswordTeacher/', views.changePasswordTeacher,
         name='changePasswordTeacher'),
    path('changePhoto/', views.changePhoto, name='changePhoto'),
    path('changePhotoTeacher/', views.changePhotoTeacher,
         name='changePhotoTeacher'),
    path('search/', views.search, name='search'),
    path('error/', views.error, name='error'),
]
